### ISSUE TITLE
`prettyPrint` is no longer supported after migrating to Fastify v4

### ISSUE THREAD

**Issue by wd-David** [ManUtopiK/vite-fastify-boilerplate#8]
Hi @ManUtopiK, first thank you for this great boilerplate.

After upgrading `fastify` to 4.0.0, the below error message would show up in development:
`Error: prettyPrint option is no longer supported, see the pino-pretty package (https://github.com/pinojs/pino-pretty)`

This can be addressed by using [`transport`](https://github.com/pinojs/pino/blob/master/docs/transports.md).

I can open a PR if you think it's OK to bump `fastify` version to v4, thanks.

**Comment by ManUtopiK** [comment]
Thanks for your feedback. I haven't got time to test Fastify v4 for now.
I'm not sure `vite-plugin-node` is compatible.
I'll try to do that at the end of this week...
